### ISSUE TITLE
Feature with 'NaN'

### ISSUE THREAD

**Issue by stillbetter** [jarikorhonen/nr-vqa-consumervideo#4]
Hi Jari, when I modify the code to my own database, I found there was 'NaN' in one video feature.

I don't know how the NaN come? Have you ever met this?

**Comment by jarikorhonen** [comment]
No, I have not met NaN, but the code is of course not bullet-proof, there may be a bug. If the video file is somewhere available, I could try to reproduce the problem, otherwise it is impossible to say what is wrong.

**Comment by stillbetter** [comment]
That's great! I will send it to your corresponding email in paper TLVQM right now, with a detail description of my process procedure.

**Comment by jarikorhonen** [comment]
I was not able to reproduce the result, but there seems to be an error on lines 92-93 in compute_nrvqa_features.mat, they should be:

```
            if std(LC_features_all(i_start:i_end,1))>0 && ...
               std(LC_features_all(i_start:i_end,11))>0
```

I have changed it in the file now. I expect that should solve the issue.

**Comment by stillbetter** [comment]
Great! I retry the code. It runs smoothly without any error! 

But I still have a question. When the frame rates is not a integrity. What should I set as the value of 'frates'  or 'blklen'? I just set it as 30 or  24, no matter the actual value is 29.97 or 23.97.

Because I think ,from the meaning of the frates and blklen it shouldn't be a float. I don't know if I treat this properly.

**Comment by jarikorhonen** [comment]
Basically, blklen is the length of the block of frames used as a basic processing unit. The algorithm picks up one representative frame from each block of frames to compute the high complexity features. It is just an agreement that blklen should be the same as the frame rate, it can be basically any integer, but of course small values will make the algorithm very slow. So it should work fine if you just round blklen to the closest integer.

In the example code, frates is just an integer for the frame rate. If the dataset contains videos with different frame rates, it could be of course a vector with different value for each video. In my experiments with videos with different frame rates, I also used frame rate as an additional feature (normalized by dividing it by 30, because I assumed that 30 is the largest frame rate). In the same way, resolution was also used as a feature (horizontal dimension divided by 1920, because I assumed 1920x1080 is the maximum resolution). These two features do not have a major impact on the results, however.
